from app.models import db, ListItem, environment, SCHEMA
from sqlalchemy.sql import text


def seed_list_items():
    li_1 = ListItem(description='JavaScript', list_id=1, is_complete=True)
    li_2 = ListItem(description='HTML', list_id=1, is_complete=True)
    li_3 = ListItem(description='CSS', list_id=1)
    li_4 = ListItem(description='Python', list_id=1)
    li_5 = ListItem(description='C++', list_id=1)
    li_6 = ListItem(description='iPhone', list_id=2, is_complete=True)
    li_7 = ListItem(description='MacBook', list_id=2)
    li_8 = ListItem(description='AirPods', list_id=2, is_complete=True)
    li_9 = ListItem(description='iPad', list_id=2)
    li_10 = ListItem(description='AirTag', list_id=2, is_complete=True)
    li_11 = ListItem(description='HomePod', list_id=2)
    li_12 = ListItem(description='Meta', list_id=3)
    li_13 = ListItem(description='Apple', list_id=3)
    li_14 = ListItem(description='Microsoft', list_id=3)
    li_15 = ListItem(description='Google', list_id=3)
    li_16 = ListItem(description='Netflix', list_id=3)
    li_17 = ListItem(description='Tsujita LA', list_id=4, is_complete=True)
    li_18 = ListItem(description='Tsujita Annex', list_id=4, is_complete=True)
    li_19 = ListItem(description='Killer Noodle', list_id=4, is_complete=True)
    li_20 = ListItem(description='Tatsu Ramen', list_id=4)
    li_21 = ListItem(description='Marugame Udon', list_id=4, is_complete=True)
    li_22 = ListItem(description='Chicken Biscuit', list_id=5)
    li_23 = ListItem(description='Spicy Chicken Biscuit', list_id=5, is_complete=True)
    li_24 = ListItem(description='Chick-n Minis', list_id=5, is_complete=True)
    li_25 = ListItem(description='Egg White Grill', list_id=5)
    li_26 = ListItem(description='Hash Brown Scramble Burrito', list_id=5)
    li_27 = ListItem(description='Bacon Egg Cheese Biscuit', list_id=5)
    li_28 = ListItem(description='Sausage Egg Cheese Muffin', list_id=5, is_complete=True)
    li_29 = ListItem(description='Tree Watching @ Sequoia or Redwoods', list_id=6)
    li_30 = ListItem(description='Swimming @ Santa Monica Beach', list_id=6)
    li_31 = ListItem(description='Geyser Watching @ Yellowstone', list_id=6)
    li_32 = ListItem(description='Star Gazing @ Joshua Tree', list_id=6)
    li_33 = ListItem(description='Bear Mountain', list_id=7, is_complete=True)
    li_34 = ListItem(description='Mammoth Mountain', list_id=7)
    li_35 = ListItem(description='Whistler', list_id=7)
    li_36 = ListItem(description='Copper Mountain', list_id=7, is_complete=True)
    li_37 = ListItem(description='Jackson Hole', list_id=7)
    li_38 = ListItem(description='Mt. Hood', list_id=7)
    li_39 = ListItem(description='Palisades Tahoe', list_id=7)
    li_40 = ListItem(description='Brighton Resort', list_id=7, is_complete=True)
    li_41 = ListItem(description='Badminton', list_id=8)
    li_42 = ListItem(description='Pickleball', list_id=8)
    li_43 = ListItem(description='Pottery', list_id=8)
    li_44 = ListItem(description='Rug Making', list_id=8)
    li_45 = ListItem(description='Barbie', list_id=9)
    li_46 = ListItem(description='Oppenheimer', list_id=9, is_complete=True)
    li_47 = ListItem(description='The Summer I Turned Pretty', list_id=10)
    li_48 = ListItem(description='Only Murders in the Building', list_id=10, is_complete=True)
    li_49 = ListItem(description='Jack Reacher', list_id=10)
    li_50 = ListItem(description='Chicago', list_id=11, is_complete=True)
    li_51 = ListItem(description='New York City', list_id=11, is_complete=True)
    li_52 = ListItem(description='Hawaii', list_id=11)
    li_53 = ListItem(description='New Orleans', list_id=11)
    li_54 = ListItem(description='a TON of baby\'s breath', list_id=12)
    li_55 = ListItem(description='bouquet holders for the bridesmaids', list_id=12)
    li_56 = ListItem(description='boutonniere holders for the suited men', list_id=12)
    li_57 = ListItem(description='lots of roses ~', list_id=12, is_complete=True)
    li_58 = ListItem(description='vases for table centerpieces', list_id=12, is_complete=True)
    li_59 = ListItem(description='flower holders for the pews', list_id=12)
    li_60 = ListItem(description='lots and lots of loose petals for the flower girls', list_id=12)
    li_61 = ListItem(description='Sequoia National Park - CA', list_id=13, is_complete=True)
    li_62 = ListItem(description='Zion National Park - UT ', list_id=13, is_complete=True)
    li_63 = ListItem(description='Redwood National Park - CA', list_id=13)
    li_64 = ListItem(description='Everglades National Park - FL', list_id=13)
    li_65 = ListItem(description='Haleakala National Park - HI', list_id=13)
    li_66 = ListItem(description='Katmai National Park - AK', list_id=13)
    li_67 = ListItem(description='Yellowstone National Park - WY', list_id=13)
    li_68 = ListItem(description='Knife Pleat, Costa Mesa (1 star)', list_id=14)
    li_69 = ListItem(description='Kato, Los Angeles (1 star)', list_id=14)
    li_70 = ListItem(description='Hayato, Los Angeles (2 stars)', list_id=14)
    li_71 = ListItem(description='Providence, Hollywood (2 stars)', list_id=14)
    li_72 = ListItem(description='Quince, San Francisco (3 stars)', list_id=14)
    
    # li_73 = ListItem(description='', list_id=, is_complete=)
    # li_74 = ListItem(description='', list_id=, is_complete=)
    # li_75 = ListItem(description='', list_id=, is_complete=)
    # li_76 = ListItem(description='', list_id=, is_complete=)
    # li_77 = ListItem(description='', list_id=, is_complete=)
    # li_78 = ListItem(description='', list_id=, is_complete=)
    # li_79 = ListItem(description='', list_id=, is_complete=)
    # li_80 = ListItem(description='', list_id=, is_complete=)
    # li_81 = ListItem(description='', list_id=, is_complete=)
    # li_82 = ListItem(description='', list_id=, is_complete=)
    # li_83 = ListItem(description='', list_id=, is_complete=)
    # li_84 = ListItem(description='', list_id=, is_complete=)
    # li_85 = ListItem(description='', list_id=, is_complete=)
    # li_86 = ListItem(description='', list_id=, is_complete=)
    # li_87 = ListItem(description='', list_id=, is_complete=)
    # li_88 = ListItem(description='', list_id=, is_complete=)
    # li_89 = ListItem(description='', list_id=, is_complete=)
    # li_90 = ListItem(description='', list_id=, is_complete=)
    # li_91 = ListItem(description='', list_id=, is_complete=)
    # li_92 = ListItem(description='', list_id=, is_complete=)
    # li_93 = ListItem(description='', list_id=, is_complete=)
    # li_94 = ListItem(description='', list_id=, is_complete=)
    # li_95 = ListItem(description='', list_id=, is_complete=)
    # li_96 = ListItem(description='', list_id=, is_complete=)
    # li_97 = ListItem(description='', list_id=, is_complete=)
    # li_98 = ListItem(description='', list_id=, is_complete=)
    # li_99 = ListItem(description='', list_id=, is_complete=)
    # li_100 = ListItem(description='', list_id=, is_complete=)

    db.session.add_all([
        li_1, li_2, li_3, li_4, li_5, li_6, li_7, li_8, li_9, li_10,
        li_11, li_12, li_13, li_14, li_15, li_16, li_17, li_18, li_19, li_20,
        li_21, li_22, li_23, li_24, li_25, li_26, li_27, li_28, li_29, li_30,
        li_31, li_32, li_33, li_34, li_35, li_36, li_37, li_38, li_39, li_40,
        li_41, li_42, li_43, li_44, li_45, li_46, li_47, li_48, li_49, li_50,
        li_51, li_52, li_53, li_54, li_55, li_56, li_57, li_58, li_59, li_60,
        li_61, li_62, li_63, li_64, li_65, li_66, li_67, li_68, li_69, li_70,
        li_71, li_72
        # , li_73, li_74, li_75, li_76, li_77, li_78, li_79, li_80,
        # li_81, li_82, li_83, li_84, li_85, li_86, li_87, li_88, li_89, li_90,
        # li_91, li_92, li_93, li_94, li_95, li_96, li_97, li_98, li_99, li_100
    ])
    db.session.commit()


def undo_list_items():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.list_items RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM list_items"))

    db.session.commit()
